### ISSUE TITLE
模板工程不存在

### ISSUE THREAD

**Issue by lihong2020** [zlgopen/ametal#19]
21届校招新入职嵌入式软件工程师，目前在学习Ametal入门到实践，书中关于ametal/board/am116_core/project_template目录下的工程模板不存在，其他目录也没有，是精简文件大小删除了吗，怎么下载呢

**Comment by wangcheng-123** [comment]
keil 工程在 ：ametal/board/am116_core/project_template/project_keil5 目录下

**Comment by lihong2020** [comment]
已找到，多谢，误进入了另外一个目录ametal/example/board/am116_core下，没看仔细
