### ISSUE TITLE
ametal_am824_core_1.02  i2c read

### ISSUE THREAD

**Issue by sunzhongmeng** [zlgopen/ametal#6]
@wangcheng-123 
ZLG的AM824-Core开发板，AMetal 软件包为 ametal_am824_core_1.02 操作 i2c设备遇到了一些问题。下边这个是我的读设备的函数：
`static uint8_t __ds90ub934_read (uint32_t sub_addr,uint32_t nbytes)
{
	uint8_t ret;
    am_i2c_read(&__g_ds90ub934_dev, 
                sub_addr, 
                &read[0], 
                nbytes);
	if(ret != AM_OK){
		AM_DBG_INFO("am_i2c_write error(id: %d).\r\n",ret);
		return 0;}
	return ret;
}`
运行时会打印：am_i2c_write error(id: 268436356)
但查看read[0]的内容，读到的数值也是正确的。

初始化函数：
`    am_i2c_mkdev(&__g_ds90ub934_dev,
                 handle,
                 0x59,
                 AM_I2C_ADDR_7BIT | AM_I2C_SUBADDR_1BYTE); `

**Comment by wangcheng-123** [comment]
你好，感谢你的及时反馈。

多次测试的结果都相同吗？返回值均为268436356吗？ 这个返回值不正常，理论上不应该出现这个返回值。如果方便的话，能否提供更详细的测试程序？

**Comment by sunzhongmeng** [comment]
> 你好，感谢你的及时反馈。
> 
> 多次测试的结果都相同吗？返回值均为268436356吗？ 这个返回值不正常，理论上不应该出现这个返回值。如果方便的话，能否提供更详细的测试程序？

你好，[测试工程链接](https://pan.baidu.com/s/1o1dkwvkgZaHENZZxBp5kyg )（提取码：uovu），工程需放在\ametal_am824_core_1.02\projects_keil5\applications目录下。

**Comment by wangcheng-123** [comment]
你好，测试工程链接无法访问，提示：此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！

**Comment by wangcheng-123** [comment]
另：无法编译的工程具体是哪个工程呢？ board_name 是？ 编译所使用的IDE是，keil5 还是 eclipse？

**Comment by sunzhongmeng** [comment]
> 你好，测试工程链接无法访问，提示：此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！

链接已经更新！

**Comment by sunzhongmeng** [comment]
> 另：无法编译的工程具体是哪个工程呢？ board_name 是？ 编译所使用的IDE是，keil5 还是 eclipse？

`\board\am824_core\project_example\project_keil5`

**Comment by wangcheng-123** [comment]
> > 另：无法编译的工程具体是哪个工程呢？ board_name 是？ 编译所使用的IDE是，keil5 还是 eclipse？
> > 我测试的这个工程无法编译：
> > `\board\am824_core\project_example\project_keil5\example_am824_core.uvprojx`

这个工程刚刚测试编译是正常的,你确认下:  你本地使用的版本是最新的吗？

**Comment by sunzhongmeng** [comment]
> > > 另：无法编译的工程具体是哪个工程呢？ board_name 是？ 编译所使用的IDE是，keil5 还是 eclipse？
> > > 我测试的这个工程无法编译：
> > > `\board\am824_core\project_example\project_keil5\example_am824_core.uvprojx`
> 
> 这个工程刚刚测试编译是正常的,你确认下: 你本地使用的版本是最新的吗？

可能是我的文件有损,更新了一下ok了.

**Comment by wangcheng-123** [comment]
使用 github 上的代码测试还有问题吗？

**Comment by sunzhongmeng** [comment]
> 使用 github 上的代码测试还有问题吗？

github上的最新代码OK,可以关闭issue了。

**Comment by wangcheng-123** [comment]
好的， 感谢你的反馈~  后续有任何问题， 欢迎及时沟通交流~
